name: wedspace
description: Aplikasi Wedding Venue Booking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.1.14
  qr_flutter: ^4.0.0
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_animate: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true